import { AIService } from "./AIService";

export const aiBeforeAfterService = {
  analyzeAndGenerate(payload, options = {}) {
    if (!AIService.isConfigured()) {
      return Promise.reject(Object.assign(new Error("AI is not configured."), { code: "AI_NOT_CONFIGURED" }));
    }

    return AIService.generateBeforeAfter(payload, options).then((aiResult) => ({
      id: globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`,
      createdAt: new Date().toISOString(),
      afterImage: aiResult.afterImage,
      provider: aiResult.provider,
      model: aiResult.model,
      prompt: {
        text: aiResult.prompt,
        projectType: payload.projectType,
        style: payload.style,
        customerWishes: payload.customerWishes || "",
        settings: {
          woodColor: payload.woodColor || "",
          wallColor: payload.wallColor || "",
          brightness: payload.brightness,
          woodAmount: payload.woodAmount,
          finishType: payload.finishType || "",
          changeLevel: payload.changeLevel,
        },
      },
      summary: "Photorealistic visualization generated by AI.",
    }));
  },
};
