function escapeSvgText(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function createDemoImage({ projectType, style, woodColor, wallColor, brightness, woodAmount, finishType, changeLevel }) {
  const safeProject = escapeSvgText(projectType);
  const safeStyle = escapeSvgText(style);
  const safeWood = escapeSvgText(woodColor || "Natural oak");
  const safeWall = escapeSvgText(wallColor || "Warm white");
  const safeFinish = escapeSvgText(finishType || "Matte");
  const brightnessValue = Math.max(0, Math.min(100, Number(brightness) || 62));
  const woodValue = Math.max(0, Math.min(100, Number(woodAmount) || 48));

  const svg = `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 900">
  <defs>
    <linearGradient id="wall" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#f4efe7"/>
      <stop offset="1" stop-color="#d9d0c2"/>
    </linearGradient>
    <linearGradient id="floor" x1="0" x2="1">
      <stop offset="0" stop-color="#8a5a2d"/>
      <stop offset="1" stop-color="#c5914b"/>
    </linearGradient>
    <radialGradient id="glow" cx="70%" cy="20%" r="55%">
      <stop offset="0" stop-color="#ffbf38" stop-opacity="0.55"/>
      <stop offset="1" stop-color="#050505" stop-opacity="0"/>
    </radialGradient>
    <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="22" stdDeviation="24" flood-color="#000" flood-opacity="0.28"/>
    </filter>
  </defs>
  <rect width="1200" height="900" fill="#111"/>
  <rect width="1200" height="900" fill="url(#glow)"/>
  <path d="M0 0h1200v540H0z" fill="url(#wall)" opacity="${0.55 + brightnessValue / 220}"/>
  <path d="M0 540h1200v360H0z" fill="url(#floor)"/>
  <g opacity="0.45">
    ${Array.from({ length: 18 }).map((_, index) => `<path d="M${index * 78 - 60} 560l150 330" stroke="#f3c06a" stroke-width="5"/>`).join("")}
  </g>
  <g filter="url(#shadow)">
    <rect x="96" y="128" width="388" height="340" rx="8" fill="#1d1d1f"/>
    <rect x="116" y="148" width="348" height="300" rx="4" fill="#f7f0e6"/>
    <path d="M116 370c88-72 148-92 222-40 38 26 69 35 126 14v104H116z" fill="#d69534" opacity="${0.45 + woodValue / 180}"/>
    <circle cx="380" cy="238" r="52" fill="#f6b02c" opacity="0.82"/>
  </g>
  <g filter="url(#shadow)">
    <rect x="600" y="190" width="410" height="382" rx="14" fill="#171719"/>
    <rect x="632" y="222" width="346" height="318" rx="8" fill="#2a2a2d"/>
    <path d="M650 505h310v35H650z" fill="#c58a43"/>
    <path d="M676 250h88v255h-88zM786 250h88v255h-88zM896 250h50v255h-50z" fill="#e6d7be" opacity="0.92"/>
  </g>
  <g transform="translate(112 650)">
    <rect width="976" height="116" rx="26" fill="#050505" opacity="0.78"/>
    <text x="34" y="48" fill="#ffbf38" font-family="Inter, Arial" font-size="24" font-weight="800">${safeStyle} ${safeProject}</text>
    <text x="34" y="84" fill="#f5f5f5" font-family="Inter, Arial" font-size="18">${safeWood} wood · ${safeWall} walls · ${safeFinish} finish · ${escapeSvgText(changeLevel)}</text>
  </g>
</svg>`;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

export const aiBeforeAfterService = {
  analyzeAndGenerate(payload) {
    return new Promise((resolve) => {
      window.setTimeout(() => {
        resolve({
          id: globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`,
          createdAt: new Date().toISOString(),
          afterImage: createDemoImage(payload),
          summary: "Demo visualization generated by mock AI service.",
        });
      }, 2600);
    });
  },
};
